export const START_APP_BOOTSTRAP = 'app/START_APP_BOOTSTRAP';
export const APP_BOOTSTRAP_COMPLETE_STATE = 'app/APP_BOOTSTRAP_COMPLETE_STATE';

export const CHANGE_COLOR_MODE = 'app/CHANGE_COLOR_MODE';
