export const GET_PUBLIC_RECIPES_LOADING_STATE =
  'recipe/GET_PUBLIC_RECIPES_LOADING_STATE';
export const GET_PUBLIC_RECIPES = 'recipe/GET_PUBLIC_RECIPES';
export const GET_PUBLIC_RECIPES_SUCCESS = 'recipe/GET_PUBLIC_RECIPES_SUCCESS';

export const GET_RECIPE_LOADING_STATE = 'recipe/GET_RECIPE_LOADING_STATE';

export const GET_SINGLE_RECIPE = 'recipe/GET_SINGLE_RECIPE';
export const GET_SINGLE_RECIPE_SUCCESS = 'recipe/GET_SINGLE_RECIPE_SUCCESS';
export const GET_PUBLIC_RECIPES_ERROR = 'recipe/GET_PUBLIC_RECIPES_ERROR';

export const CREATE_RECIPE_SAVING_STATE = 'recipe/CREATE_RECIPE_SAVING_STATE';
export const CREATE_RECIPE = 'recipe/CREATE_RECIPE';
export const CREATE_RECIPE_SUCCESS = 'recipe/CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE_ERROR = 'recipe/CREATE_RECIPE_ERROR';
